replicaCount: 2
namespace: "kubeapp"
metadata:
 name: book-svc 
 label: book-svc

mariadb:
  database: "SAMPLE"
  host: "mariadb.kubeapp"
  uid: "YWRtaW4="
  password: "YWRtaW4="
  secret: "aGVsbG8="

readinessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 300
image:
  name: book-svc
  imageName: "book-svc" 
  imagePullPolicy: Always
  ports:
    containerPort: 3004
  requests:
    cpu: "50m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "200Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
  
hpa:
  metadata:
    name: book-svcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: book-svc

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: cumulusairbook
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: cumulusairbook
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: cumulusairbook
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: cumulusairbook
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: cumulusairbook
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: cumulusairbook
      key: PORT
  envHOST:
    name: HOST
    configMapKeyRef:
      name: cumulusairbook
      key: HOST
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: cumulusairbook
      key: PROTOCOL


service:
  serviceMetadata:
    name: book-svc
    labels:
      app: book-svc
  selector:
    selectorName: book-svc
  servicePortConfiguration:
    protocol: TCP
    name: book-svc
    type: ClusterIP
    port: 3004
    targetPort: 3004


imagestream:
  name:  book-svc
  label: book-svc

buildconfig:
  uri: "https://github.com/cumulus-airways/booking-microservice.git"
  branch: "master"
  name: "book-svc"
  imagename: "book-svc:latest"
  secret1: $(head -c 24 /dev/random | base64)
  secret2: $(head -c 24 /dev/random | base64)

routes:
  host: "book-svc-kubeapp.apps.9.30.210.207.nip.io"
  targetPort: 3004
  name: book-svc
  weight: 100


nameOverride: ""
fullnameOverride: ""